# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j2y18lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j4primelte/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/hw/sensors.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.msm8937.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libactuator_zc535.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_zc535.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_common.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_liveshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_snapshot_lls.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_snapshot_lls.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_vt_15fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_vt_15fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_vt_30fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_vt_30fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_cpp_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_cpp_vt.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_default_video_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_default_video_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_hfr_120_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_hfr_120_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_postproc.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt_15fps_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt_15fps_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt_15fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt_15fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt_24fps_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt_24fps_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt_30fps_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt_30fps_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt_30fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt_30fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_vt.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_f2_2_zsl_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_f2_2_zsl_preview_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_1080p_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_1080p_preview_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_1080p_video_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_1080p_video_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_4k_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_4k_preview_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_4k_video_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_4k_video_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_common.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_hfr_60.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_hfr_90.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_liveshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_night.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_night.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_video_4k.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_vt_30fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_vt_30fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_vt_hd.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_cpp_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_cpp_vt.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_default_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_default_preview_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_default_video_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_default_video_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_default_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_hfr_120_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_hfr_120_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_hfr_60_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_hfr_60_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_hfr_60.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_hfr_90_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_hfr_90_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_hfr_90.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_liveshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_night_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_night_preview_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_postproc.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_video_4k.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_vt_30fps_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_vt_30fps_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_vt_30fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_vt_30fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_vt_hd_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_vt_hd_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_vt_hd.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_vt_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_vt_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_vt.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_4k_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_4k_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_4k_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_4k_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_night_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_night_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_panorama_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_panorama_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_sports_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_sports_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_vt_24fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_vt_24fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_vt_30fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_vt_30fps.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_wechat_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_wechat_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_wechat_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_wechat_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_zsl_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_3a_zsl_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_common.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_iso_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_iso_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_liveshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_lls_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_lls_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_night_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_night_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_panorama_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_panorama_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_preview.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_sports_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_sports_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_sr_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_sr_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_video_4k.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_video_wechat.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_cpp_video_wechat.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_default_video.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_hfr_120.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_iso.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_mode_iso.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_night.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_mode_night.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_mode_panorama.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_sports.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_mode_sports.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_sr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_mode_sr.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_wechat.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_mode_wechat.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_isp_snapshot.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_postproc_lds.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_postproc_lds.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_postproc_mode_sr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_postproc_mode_sr.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_y08qf_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_y08qf_postproc.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_zsl_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_zsl_preview_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libchromatix_sr846_zsl_video_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sr846_zsl_video_lc898122.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera2_sensor_debug.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_debug.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera_sr846.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sr846.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera_zc535_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_zc535_eeprom.so
