# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/msm8917-common/setup-makefiles.sh

LOCAL_VINTF_PATH := vendor/samsung/msm8917-common/proprietary/vendor/etc/vintf/manifest

DEVICE_MANIFEST_FILE += \
	$(LOCAL_VINTF_PATH)/android.hardware.gnss@2.0-service-qti.xml \
	$(LOCAL_VINTF_PATH)/vendor.qti.gnss@3.0-service.xml
